apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: fitness-support
description: main application pipeline
serialPipeline:
  stages:
    # - targetId: run-dev
    #   profiles: [dev]
    - targetId: run-prod
      profiles: [prod]
# ---
# apiVersion: deploy.cloud.google.com/v1
# kind: Target
# metadata:
#   name: run-dev
# description: Cloud Run development service
# run:
#   location: projects/{project_id}/locations/asia-northeast1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: run-prod
description: Cloud Run production service
run:
  location: projects/kyong0612-lab/locations/asia-northeast1
